import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TabBar from "./components/tab-bar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-300`}
      >
        <div className="flex items-center justify-center">
          <div className="bg-white w-96">
            <div className="mb-16">{children}</div>
            <TabBar />
          </div>
        </div>
      </body>
    </html>
  );
}
